<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=30)),
                ('tamaño', models.CharField(max_length=30)),
            ],
        ),
    ]
=======
# Generated by Django 5.2.7 on 2025-11-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=30)),
                ('tamaño', models.CharField(max_length=30)),
            ],
        ),
    ]
>>>>>>> dd686a4e1f4202362c07ebce170f5dcb86ca1bbc
